### PR TITLE
Calling resize on each and every window resize drammatically slows down the browser

### LINKED ISSUE #857: Calling resize on each and every window resize drammatically slows down the browser
If you have a lot of charts and use Firefox (this issue appears in other browsers as well, but it slows down especially Firefox), resizing the window can be a huge pain (resizing is fired not only when you resize the window itself, but also when you open Firebug, for example). This happens because `$$.api.flush();` is called on every resize event call. Which can be tens of times. Instead of calling it on each resize event call, I suggest using the following code:

```js
        if (window.onresize.add) {
            var timeout;
            window.onresize.add(function () {
                config.onresize.call($$);
            });
            if (config.auto_resize) {
                window.onresize.add(function () {
                    if (timeout !== undefined) {
                        clearTimeout(timeout);
                    }
                    timeout = setTimeout(function() {
                        $$.api.flush();
                    }, 100);
                });
            }
            window.onresize.add(function () {
                config.onresized.call($$);
            });
        }
```

`$$.api.flush()` will be called not more than once per 100ms (the number is random here, I didn't make a lot of tests, which one is the best).

Also, please note `auto_resize` setting. It could be used to turn off auto resizing the charts. By default it should be true for backwards code compatibility.

I hope, you got my idea and this can go to the core.

### PR DESCRIPTION
**Pull request by denisvmedia**
This commit resolves #857

### CODE REVIEW

**Comment by masayuki0812** [comment]
Hi,
Thank you very much for this fix!! Your code looks nice, but one thing, can you change `auto.resize` to `resize.auto`? It looks more c3-way for me.

**Comment by denisvmedia** [comment]
I updated the name (the first commit in the update has a wrong comment though, but internally it's correct; I'm sorry for that).

**Comment by aendrew** [comment]
Hi @denisvmedia! Could you please squash your commits?

`git rebase -i HEAD~3` -- [more info](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html)

**Comment by ajainarayanan** [comment]
Is this change still going in by any chance? This improves the performance by so much.

**Comment by masayuki0812** [comment]
@denisvmedia Sorry for the late response. Thanks!!

**Pull request merged**
