### PR TITLE
Resolved #305; Now you may pass axis.y.tick.rotate

### LINKED ISSUE #305: Allow y axis to have tick.rotate
Especially useful when working with charts with rotated axes.

### PR DESCRIPTION
**Pull request by Timopheym**
If this will be approved I can make for y2 too.
I need it for my project anyway.

### CODE REVIEW

**Comment by aendrew** [comment]
I haven't cloned your branch locally to test yet, but LGTM just by looking at the commit. :+1:

**Comment by Timopheym** [comment]
Test failed at  ```c3 chart arc => show pie chart```
It was by me *sometimes* too, do you have an idea why?

**Comment by aendrew** [comment]
@Timopheym There've been a few PRs that've have sporadically failed testing; there might be a race condition in the tests somewhere, will take a solid look at it on Monday.

**Comment by Timopheym** [comment]
Thanks =)

On Sat, Mar 7, 2015 at 9:14 PM, Ændrew Rininsland <notifications@github.com>
wrote:

> @Timopheym <https://github.com/Timopheym> There've been a few PRs that've
> have sporadically failed testing; there might be a race condition in the
> tests somewhere, will take a solid look at it on Monday.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/masayuki0812/c3/pull/1047#issuecomment-77701799>.
>



-- 
Kind regards,
Timophey Molchanov.

First do it, then do it right, then do it fast.

**Comment by masayuki0812** [comment]
Fixed spec to have `axis.rotated = true` because tick rotate is supported on bottom axis currently.

**Comment by aendrew** [comment]
:+1: :tada: :confetti_ball: Yay!

**Pull request merged**
