### PR TITLE
Adds Sass support

### PR DESCRIPTION
**Pull request by aendrew**
See #803. I've separated c3.css into its component parts and pulled all those into main.scss, which gets written to c3.css (and minified during the default `grunt` task). I haven't optimised or organised the scss files any further than that.

Might be worth considering optimising these into more readable SCSS, in addition to adding [grunt-autoprefixer](https://github.com/nDmitry/grunt-autoprefixer) to automatically add vendor prefixes where necessary.

### CODE REVIEW

**Comment by aendrew** [comment]
@masayuki0812 Any thought on whether this is desirable? Personally, I think it'd be really helpful for making everything more modular. If you plan to merge this, please let me know and I'll resolve the current conflicts ASAP. Thanks!

**Comment by jmnunezizu** [comment]
@aendrew Why not use Stylus instead? I'd rather have Stylus and carry on with Node.js/JavaScript than introduce Ruby to the mix.

**Comment by aendrew** [comment]
@jmnunezizu I've never used Stylus, but node-sass uses the C++ version of Compass — Ruby-free!

**Comment by jmnunezizu** [comment]
@aendrew I haven't used Sass extensively (happy stylus user myself) but I trust your judgement.

**Comment by masayuki0812** [comment]
@aendrew Sorry for late response.. I think it's ok to merge this PR basically, so could you fix the conflict? Thank you.

**Comment by aendrew** [comment]
@masayuki0812 No worries! I've updated the PR to merge successfully, as well as changed it from `grunt-contrib-sass` to `grunt-sass` as per the point above.

**Comment by mschipperheyn** [comment]
Yeah, I actually find it extremely hard to manage the styles. Somehow, it interferes with my css styling I use for our site (bootstrap). I'm on less myself. But I suppose that it's easy to convert

**Comment by masayuki0812** [comment]
Looks very nice. Thanks!

**Comment by aendrew** [comment]
Woo! Thanks @masayuki0812! :+1: :shipit:

**Pull request merged**
