### PR TITLE
Add button for professional services

### PR DESCRIPTION
**Pull request by SupportedSource**
The button takes people here:

http://supportedsource.org/consulting-services-and-support/c3

Anyone who seems credible can contact us at supportedsource.org/contact to get on the list of service providers.

### CODE REVIEW

**Comment by aendrew** [comment]
:+1: I'm in support of adding this, though two issues:

1. Could you please squash your commits?
2. The PNG being output from your site looks really shoddy on retina displays.

screen shot 2015-07-29 at 12 59 22

Might be asking a bit, am aware, but any chance you could make that look a bit better?

Thanks!

**Comment by SupportedSource** [comment]
Sure, I'll squash the commits in a sec.

I don't have a retina screen, so I guess I never noticed it. I'll look into it though but not part of this PR. I'll let you know if/when I get a higher resolution version.

**Comment by j-schumann** [comment]
URL http://supportedsource.org/consulting-services-and-support/c3 is (no longer) reachable, serves Heroku error.

**Comment by aendrew** [comment]
@j-schumann Good spot. Closing as now irrelevant.

**Pull request closed without merging**
