### PR TITLE
Fixed getParentRectValue exception in IE #712

### PR DESCRIPTION
**Pull request by DarkoKukovec**
Solves the issue happening in IE11: https://github.com/masayuki0812/c3/issues/712

### CODE REVIEW

**Comment by hkjels** [comment]
+1
Entirely broken in IE without this fix

**Comment by masayuki0812** [comment]
Merged. Thanks!!

**Comment by masayuki0812** [comment]
I merged #1057 as well.

**Comment by masayuki0812** [comment]
Maybe #1056 is related.

**Comment by yordis** [comment]
Oh GOD, you saved me from 10 tickets related to this for this release ROFL. Thanks a lot!!!!!!!! :smile:

**Pull request merged**
