### PR TITLE
#1602 - Makes Unfilled Portion of Gauge Visible

### PR DESCRIPTION
**Pull request by Kinlaw**
Fixes the problem with gauge where a full circle gauge does not show the portion of the gauge that is not filled (#1602).

### CODE REVIEW

**Comment by coreymaher** [comment]
Any chance 3e40d03fcb00175231a1ecadabd11c8c280521ba is going to get merged in?

**Comment by Kinlaw** [comment]
@coreymaher my bad. I dropped the ball on this one. I'll see if I can't pick this back up this week.

**Comment by coreymaher** [comment]
No problem, but it would be nice to have this functionality if you get around to it.

**Comment by Kinlaw** [comment]
@coreymaher I opened a new PR for this since the old one was so old. #2282

**Pull request closed without merging**
